version: '3'

volumes:
  db-data:

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: always
    volumes:
      - ./src:/app/src
    depends_on:
      - db
  db:
    image: postgres:14
    container_name: blog-training-db
    volumes:
      - db-data:/var/lib/postgresql/coopello_todo_db_development/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
