version: '3'

volumes:
  db-data:

networks:
  network1:

services:
  db:
    image: postgres:14
    container_name: coopello-todo-db
    volumes:
      - db-data:/var/lib/postgresql/coopello_todo_db_development/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      TZ: 'Asia/Tokyo'
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    networks:
      - network1
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: always
    volumes:
      - ./src:/app/src
    depends_on:
      - db
    networks:
      - network1
